import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Modality } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Server-side Gemini Client
  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // API endpoint for generating music
  app.post("/api/generate-music", async (req, res) => {
    try {
      const { prompt, genre } = req.body;
      if (!prompt) {
        return res.status(400).json({ error: "Prompt is required" });
      }

      const fullPrompt = `${genre || "synth"} music: ${prompt}. Generate a high-fidelity 30-second audio track.`;

      // Call Gemini API on the server side
      const response = await ai.models.generateContentStream({
        model: "lyria-3-clip-preview",
        contents: fullPrompt,
        config: {
          responseModalities: [Modality.AUDIO],
        }
      });

      let audioBase64 = "";
      let lyrics = "";
      let mimeType = "audio/wav";

      for await (const chunk of response) {
        const parts = chunk.candidates?.[0]?.content?.parts;
        if (!parts) continue;
        for (const part of parts) {
          if (part.inlineData?.data) {
            if (!audioBase64 && part.inlineData.mimeType) {
              mimeType = part.inlineData.mimeType;
            }
            audioBase64 += part.inlineData.data;
          }
          if (part.text) {
            lyrics += part.text;
          }
        }
      }

      if (!audioBase64) {
        return res.status(500).json({ 
          error: "No audio was generated by the model. Check that your user account has the required credentials." 
        });
      }

      res.json({
        audioBase64,
        lyrics,
        mimeType
      });
    } catch (error: any) {
      console.error("Gemini Music Generation Error:", error);
      res.status(error.status || 500).json({
        error: error.message || "Failed to generate music",
        code: error.code || 500,
        status: error.status || "INTERNAL_ERROR"
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
